---
title: "Capstone EDA/Cleaning"
author: "Walt Ames"
date: "7/22/2019"
output: html_document
---


```{r}

rm(list = ls(all = TRUE)) 

# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(dplyr)
library(psych)
```

```{r}
master <- read_csv("master.csv")
improvement <- read_csv("full_improvement_update.csv")
```

```{r}
master <- master %>% inner_join(improvement, by = "Parcel_Number")
```


```{r}
#Having an issues with this line of code, it is removing all incomplete buildings but alsoo 1 vs 1.0 so we are losing some
# values, need to discuss what percent complete we should filter for (if any) as incomplete buildings can be sold during #construction process.  Curious what everyone thinks.  - Walt

#master <- master %>% filter(percent_complete >= 1.0)
```

```{r}
master <- master %>% select(-c(Appraisal_Date, percent_complete, X1.x, X1.y, row_num))
```

```{r}
master <- master %>% filter(between(sale_price, 20000, 705000),
                            (between(Land_Net_Acres, .05, 10)),
                             (between(square_feet, 190, 5000)),
                            bedrooms <= 6,
                            between(bathrooms, 1, 5),
                            between(stories, 1, 5))
                          
```


```{r}
skim(master)
```

```{r}
summary(master)
```

```{r}
master <- master %>%
      mutate(withInSewerImprovement = ifelse(withInSewerImprovement == "N",0,1)) %>%
      mutate(near_firestation = ifelse(near_firestation == "N",0,1)) %>%
      mutate(near_healthcare = ifelse(near_healthcare == "N",0,1)) %>%
      mutate(near_libraries = ifelse(near_libraries == "N",0,1)) %>%
      mutate(near_policestation = ifelse(near_policestation == "N",0,1)) %>%
      mutate(near_schools = ifelse(near_schools == "N",0,1)) %>%
      mutate(near_waterplants = ifelse(near_waterplants == "N",0,1))
```



```{r}
master[!is.na(master['View_Quality']),'View_Quality'] <- 1
master[is.na(master['View_Quality']),'View_Quality'] <- 0
master[!is.na(master['Waterfront_Type']),'Waterfront_Type'] <- 1
master[is.na(master['Waterfront_Type']),'Waterfront_Type'] <- 0
master <- 
  master %>%
  mutate(
    Utility_Sewer = as.factor(Utility_Sewer),
    Utility_Water = as.factor(Utility_Water),
    Utility_Electric = as.factor(Utility_Electric),
    View_Quality= as.factor(View_Quality),
    Waterfront_Type = as.factor(Waterfront_Type),
    withInSewerImprovement = as.factor(withInSewerImprovement),
    near_firestation = as.factor(near_firestation),
    near_healthcare = as.factor(near_healthcare),
    near_libraries = as.factor(near_libraries),
    near_policestation = as.factor(near_policestation),
    near_schools = as.factor(near_schools),
    near_waterplants = as.factor(near_waterplants),
    condition = as.factor(condition),
    quality = as.factor(quality),
    attic_finished_square_feet = as.factor(attic_finished_square_feet),
    basement_square_feet = as.factor(basement_square_feet),
    basement_finished_square_feet = as.factor(basement_finished_square_feet),
    porch_square_feet = as.factor(porch_square_feet),
    attached_garage_square_feet = as.factor(attached_garage_square_feet),
    detached_garage_square_feet = as.factor(detached_garage_square_feet)
  )
master <- master %>%
  mutate(
      Utility_Sewer = case_when(
      Utility_Sewer == "SEWER/SEPTIC AVAIL" ~ "1",
      Utility_Sewer == "SEWER/SEPTIC INSTALLED" ~"2",
      Utility_Sewer == "SEWER/SEPTIC NO" ~"0",
      Utility_Sewer == "SEWER/SEPTIC NO PERC" ~"0"
    ),
    Utility_Electric = case_when(
      Utility_Electric == "POWER AVAILABLE" ~ "1",
      Utility_Electric == "POWER INSTALLED" ~"2",
      Utility_Electric == "POWER NO - COMMENT" ~"0"
    ),
    Utility_Water = case_when(
    Utility_Water == "WATER AVAILABLE" ~ "1",
    Utility_Water == "WATER INSTALLED" ~"2",
    Utility_Water == "WATER NO" ~"0"
    ),
    Utility_Sewer = as.factor(Utility_Sewer),
    Utility_Electric = as.factor(Utility_Electric),
    Utility_Water = as.factor(Utility_Water)
  )
master[is.na(master['Utility_Sewer']),'Utility_Sewer'] <- '2'
master[is.na(master['Utility_Water']),'Utility_Water'] <- '2'
master[is.na(master['Utility_Electric']),'Utility_Electric'] <- '2'
```

```{r}
master <- master %>%
  select(-Utility_Sewer,-Utility_Water,-Utility_Electric)
```

```{r}
summary(master)
```
### correlation 

```{r}

categorical <- master %>%
  select(View_Quality,Waterfront_Type, 
         near_firestation, near_healthcare, near_libraries, near_policestation, near_waterplants,
         near_schools, withInSewerImprovement, condition,  quality,attic_finished_square_feet,basement_square_feet,porch_square_feet,attached_garage_square_feet,detached_garage_square_feet)
Numeric <- master %>%
  select(Crime_Num,square_feet, fireplaces, stories, bedrooms, bathrooms,year_built, sale_price)
```

### 
```{r}
chisq.test(table(master$View_Quality,master$Waterfront_Type))
```

```{r}
chisq.test(table(master$near_firestation,master$near_healthcare))
chisq.test(table(master$near_policestation,master$near_waterplants))
chisq.test(table(master$near_policestation,master$near_firestation))
chisq.test(table(master$near_libraries,master$near_firestation))
chisq.test(table(master$near_policestation,master$near_libraries))
chisq.test(table(master$near_libraries,master$near_schools))
chisq.test(table(master$porch_square_feet,master$basement_square_feet))
chisq.test(table(master$condition,master$quality))
chisq.test(table(master$attached_garage_square_feet,master$detached_garage_square_feet))
```

```{r fig.width= 10}
pairs.panels(categorical)

```


```{r}

cor(Numeric,use = "na.or.complete")
pairs.panels(Numeric)
```


```{r}
plot(bathrooms ~ square_feet, data = master)
abline(lm(bathrooms ~ square_feet, data = master))
```

